/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PracticeSettings {
  duration: number;
  mode: string;
  num_questions: number;
  toefl_score: string;
}
